apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 7777 # Cổng tùy chọn (30000-32767)
  type: NodePort