pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: test
    image: alpine
    command: ['sh', '-c', 'echo Hello from Kubernetes agent']
"""
    }
  }
  stages {
    stage('Test') {
      steps {
        container('test') {
          sh 'echo "Jenkins agent chạy trong pod Kubernetes thành công!"'
        }
      }
    }
  }
}
