def ECR_IMAGE = "123456789012.dkr.ecr.ap-southeast-1.amazonaws.com/app1"
def IMAGE_TAG = "build-${env.BUILD_NUMBER}"

podTemplate(
    label: 'kaniko-maven-pod',
    containers: [
        containerTemplate(
            name: 'maven',
            image: 'maven:3.9.6-eclipse-temurin-17',
            command: '',
            ttyEnabled: true
        ),
        containerTemplate(
            name: 'kaniko',
            image: 'gcr.io/kaniko-project/executor:latest',
            ttyEnabled: true,
            command: '/kaniko/executor',
            args: "--dockerfile=Dockerfile --context=/workspace --destination=${ECR_IMAGE}:${IMAGE_TAG} --verbosity=info",
            workingDir: '/workspace'
        )
    ],
    volumes: [
        secretVolume(
            mountPath: '/kaniko/.docker',
            secretName: 'ecr-secret'
        ),
        emptyDirVolume(mountPath: '/workspace')
    ]
) {
    node('kaniko-maven-pod') {

        stage('Checkout') {
            // Đảm bảo code nằm trong /workspace để kaniko sử dụng
            dir('/workspace') {
                checkout scm
            }
        }

        stage('Maven Build') {
            container('maven') {
                dir('/workspace') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        // Không cần stage Kaniko vì container đã build khi start
    }
}
