pipeline {
  agent {
    kubernetes {
      yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    tty: true
    volumeMounts:
      - name: workspace-volume
        mountPath: /workspace
      - name: docker-config
        mountPath: /kaniko/.docker
  - name: jnlp
    image: jenkins/inbound-agent:latest
    tty: true
  volumes:
    - name: workspace-volume
      emptyDir: {}
    - name: docker-config
      secret:
        secretName: ecr-secret  # <- Tên secret chứa config để push ECR
"""
    }
  }

  stages {
    stage('Test') {
      steps {
        container('kaniko') {
//           sh 'echo "Jenkins agent chạy trong pod Kubernetes thành công!"'
        }
      }
    }
  }
}
